/*
   import The ObjectId type that represents a unique identifier
   generated by MongoDB for each document in a collection
*/
use mongodb::bson::oid::ObjectId;
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct User {
    #[serde(rename = "_id", skip_serializing_if = "Option::is_none")]
    /*
       #[serde()] is an attribute macro from the serde crate.
       It specifies how the field id should be serialized and deserialized.
       The "rename" attribute renames the field to "_id" when serializing
       and deserializing.

       The "skip_serializing_if" attribute is used to conditionally skip
       the field if its value is None.

       In this case, if the id field is None,
       it won't be included in the serialized output.
    */
    pub id: Option<ObjectId>,
    pub name: String,
    pub location: String,
    pub title: String,
}
